#!/bin/bash

echo "🚀 Git Setup Instructions"
echo "========================="
echo ""
echo "1. Create GitHub repository:"
echo "   - Go to https://github.com"
echo "   - Click 'New repository'"
echo "   - Name: cafeteria-management-system"
echo "   - Don't initialize with README"
echo "   - Click 'Create repository'"
echo ""
echo "2. Connect and push (replace YOUR_USERNAME):"
echo ""
echo "git branch -M main"
echo "git remote add origin https://github.com/YOUR_USERNAME/cafeteria-management-system.git"
echo "git push -u origin main"
echo ""
echo "3. Alternative: Use SSH (if you have SSH keys):"
echo "git remote add origin git@github.com:YOUR_USERNAME/cafeteria-management-system.git"
echo ""
echo "Your project is ready to push! 🎉"