name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Copy root pom for Sonar
        run: |
          cat > pom.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>
              <groupId>com.houari</groupId>
              <artifactId>iamneo-production_0b6d58ad-b187-431b-a5e1-0eb2a40b59fb-4a743646-990e-42f7-8c60-f0d5127a7a0d</artifactId>
              <version>1.0-SNAPSHOT</version>
              <properties>
                  <maven.compiler.source>17</maven.compiler.source>
                  <maven.compiler.target>17</maven.compiler.target>
                  <sonar.organization>iamneo-production</sonar.organization>
                  <sonar.host.url>https://sonar.server.examly.io</sonar.host.url>
                  <sonar.sources>springapp/src/main</sonar.sources>
                  <sonar.java.binaries>springapp/target</sonar.java.binaries>
              </properties>
              <build>
                  <pluginManagement>
                      <plugins>
                          <plugin>
                              <groupId>org.sonarsource.scanner.maven</groupId>
                              <artifactId>sonar-maven-plugin</artifactId>
                              <version>3.7.0.1746</version>
                          </plugin>
                      </plugins>
                  </pluginManagement>
              </build>
          </project>
          EOF
      - name: Build Spring Boot
        run: |
          cd springapp
          mvn clean compile -DskipTests
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=iamneo-production_0b6d58ad-b187-431b-a5e1-0eb2a40b59fb-4a743646-990e-42f7-8c60-f0d5127a7a0d \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Trigger API
        if: always()
        run: |
          if [ -n "${{ secrets.API_URL }}" ] && [ -n "${{ secrets.API_SECRET }}" ]; then
            REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"repo_id\":\"$REPO_NAME\",\"branch_name\":\"$BRANCH_NAME\",\"api_secret\":\"${{ secrets.API_SECRET }}\"}\"\
              "${{ secrets.API_URL }}"
          else
            echo "API credentials not set, skipping API trigger"
          fi