name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd springapp
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=iamneo-production_0b6d58ad-b187-431b-a5e1-0eb2a40b59fb-4a743646-990e-42f7-8c60-f0d5127a7a0d \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Trigger API
        if: always()
        env:
          API_URL: ${{ secrets.API_URL }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: |
          if [ -n "$API_URL" ]; then
            REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            API_PAYLOAD="{ \"repo_id\": \"$REPO_NAME\", \"branch_name\": \"$BRANCH_NAME\", \"api_secret\": \"$API_SECRET\" }"
            curl -X POST -H "Content-Type: application/json" -d "$API_PAYLOAD" $API_URL
          else
            echo "API_URL not set, skipping API trigger"
          fi